ghcrPullDockerConfigJson: ENC[AES256_GCM,data:ymxEUjjpVkWv9wT6rX5HkYRLd9F+JQd9bzZCpnb/QUgDKL5sSAOYaPSJ5AhvEB2XiVgcz6L8Njs/w5s9OLIRI68LFu/Fp/gkzKVXRxDrrvr924UDCxoQh5Rd55kq2ClgxjaFk+YCq2YbsS2+6cQK3yBE0L1f8aOgU6H+pD0K1CHMd+x1bYv8ZnqeZOs52/OT3mFhblG6SLadWAVek7hA7CW5SlQ8XgIqpyb4Kavf5qCuNikvglzP/JFJEBGIvI+ha3V4eH4feyAf1DAjYD+NONpq9i6HerWf75BcXN/ljPnWtqV+Xjh3JVX2FFyn+5EVLDsyJkibkWuFHczVb9WaHRD1A8kQwzAiEf1jU9QUcII=,iv:95a54zK998kMBtDlKZrZf2acygFcnkQm/osBI3Urq8A=,tag:RRPNjFGTfHOcwtyDPBZGnA==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/ynet-stage/locations/global/keyRings/sops/cryptoKeys/sops-uat-key
          created_at: "2026-04-02T12:06:41Z"
          enc: CiQAMMK76ezqx/QwM9G//M0kOwk3Fz777m7ay6W3kGDw/Vtb8qUSSQC9etkIkNWwThHRkMkNO2j6nxfI/TMWb476eAD15D449G7ZZQhp4JrQlX0PMQijyYU1s2LlfpwqntGV0Fg0vw871Z4J/g4rmZQ=
    lastmodified: "2026-04-02T12:06:42Z"
    mac: ENC[AES256_GCM,data:cMtClcwu85XndRef2a4PwqESMWKkQ0YNd0wPE722FqEGFgtzXnloHPftXNYjciDS+vqWubLj79gjcTlCSFurJcoAHiaLkJZ81TdPOxU7t10FlRjwPYSKKCXXJjg/rzJCqkRO0quRhOXznvyPKAuqrJBcTo0iPJtGjDjwZZOfKRI=,iv:CNkK4C/ATnhIGsL4YWnibaW0duls4BBGhYJiNTNBXKQ=,tag:24a7H3MVs4aw4uRmieygsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
