assets:
  - name: "USD Circle"
    symbol: "usdc"
    decimals: 6
    suggested_blockchain_id: 11155111
    tokens:
      - blockchain_id: 11155111
        address: "0x6E2C4707DA119425dF2c722E2695300154652f56"
        decimals: 6
  - name: "Wrapped ETH"
    symbol: "weth"
    decimals: 18
    suggested_blockchain_id: 11155111
    tokens:
      - blockchain_id: 11155111
        address: "0x2A35728CADd8076dfD424fC3e20974A3CD03bFa5"
        decimals: 18
  - name: "Ether"
    symbol: "eth"
    decimals: 18
    suggested_blockchain_id: 11155111
    tokens:
      - blockchain_id: 11155111
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
  - name: "Yellow"
    symbol: "yellow"
    decimals: 18
    suggested_blockchain_id: 11155111
    tokens:
      - blockchain_id: 11155111
        address: "0xB1aA0ac73B5E648a57db2d9342f11c471FcC85F1"
        decimals: 18
