config:
    secretEnvs:
        NITRONODE_BLOCKCHAIN_RPC_ETHEREUM_SEPOLIA: ENC[AES256_GCM,data:C9eZOgyk62cjCaSGDNFEKU4G3Oei1yLV9ovrF7+2lMFwTz6CjQ5vmpAZtu7vSHJaR9xZZEmuvpymV4dmiOxHOdOq7FJM/tLGICcTrXV0GegS5GeCr7DrHlG6nAkgwwZDwRJqB1lqsB4MUIXxzaJptvPS27mzMEam,iv:JOV2bGKxSWgM0GiLEAbs0q9XZ9bx8lGo1anXcv4vN4w=,tag:M/l0RqzxfFkP4BJfuN83qA==,type:str]
        NITRONODE_BLOCKCHAIN_RPC_BASE_SEPOLIA: ENC[AES256_GCM,data:sVLy5GPs3+hSr2adf2EZksHw/7lnNsjW/yr5WeIHJW58eoE6gWB1A7Yo3Ng6zR9s94Yj9v9PzVzJPD1aaU6hq3IJMzV6uU5PQp4mTuxuQ0yik5mdt/sIamb+steUnfjUJww=,iv:dc2GtnPRkXyOikjVi0teOlQ6FdSowf6/BjX21ukSdHc=,tag:hfDP2Bk95FK9kuR1fSc26w==,type:str]
    database:
        password: ENC[AES256_GCM,data:wLVLlRQYE+e4rQ==,iv:2foG2y5yg2goA2fNLKMw9ESLJ9vVmS61ozbn9StQEuM=,tag:6Tl46uxUdMe12pMbSQ5XGg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/ynet-stage/locations/global/keyRings/sops/cryptoKeys/sops-uat-key
          created_at: "2026-04-02T12:14:10Z"
          enc: CiQAMMK76XoOsaEq3elJXL/OGZ/OvdDWr3hiLdfb5oQzSqJDrqESSQC9etkIbM0LvrkQHLBIV6ENlIMxX5lz/YMxBp/J5pzkO6KG3TUQ20eQmBVovw0EI1lEox7J1GtLwENfBfcYFCy1us7df6/0JNI=
    lastmodified: "2026-05-27T09:25:28Z"
    mac: ENC[AES256_GCM,data:LrhABVJ46c8SGF5uRvk+WxfB0ocjaE11OOj+Yen4W8SJ3AtZnjdws5PFHseJSDUl9e0CkBXwiml+74WZ2A7YQpwzDTf3F2/R4W7a4yW49NaCsgj/0Nt14pGgVOQ0bdwcnJhZWiZbzsbHQ+5NmKfLQKG7SxavrjjnNljcaSNZIHc=,iv:DSgyBbMgGkBnJRotkETBCO35t2lO/BlpOQr48Q8Mqmk=,tag:xhD87+T6doRRBSmZ6tNKqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
