config:
    secretEnvs:
        NITRONODE_BLOCKCHAIN_RPC_ETHEREUM_SEPOLIA: ENC[AES256_GCM,data:C9eZOgyk62cjCaSGDNFEKU4G3Oei1yLV9ovrF7+2lMFwTz6CjQ5vmpAZtu7vSHJaR9xZZEmuvpymV4dmiOxHOdOq7FJM/tLGICcTrXV0GegS5GeCr7DrHlG6nAkgwwZDwRJqB1lqsB4MUIXxzaJptvPS27mzMEam,iv:JOV2bGKxSWgM0GiLEAbs0q9XZ9bx8lGo1anXcv4vN4w=,tag:M/l0RqzxfFkP4BJfuN83qA==,type:str]
        NITRONODE_BLOCKCHAIN_RPC_BASE_SEPOLIA: ENC[AES256_GCM,data:FpBz6s7hkf+vPpskaNyzhJW/9TvPNnV9LVgEOIbbaYTOPHxFOHPOPy012sqhTgu0Tw19nZE4dqj2McOk3ma7k1kBzxDv2DFMTl+xM55eWYSFBSrSnkgKcJ4y4sxbnHOV/t6kvKzzGy/fR2LlX4qeP24W5dQ=,iv:muH6m/wp4jWf8NoV4aD/NIBFvggtK2Hcvb8DuFBeGTg=,tag:WDKV+rTLOSIsZGlGju9DIw==,type:str]
    database:
        password: ENC[AES256_GCM,data:wLVLlRQYE+e4rQ==,iv:2foG2y5yg2goA2fNLKMw9ESLJ9vVmS61ozbn9StQEuM=,tag:6Tl46uxUdMe12pMbSQ5XGg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/ynet-stage/locations/global/keyRings/sops/cryptoKeys/sops-uat-key
          created_at: "2026-04-02T12:14:10Z"
          enc: CiQAMMK76XoOsaEq3elJXL/OGZ/OvdDWr3hiLdfb5oQzSqJDrqESSQC9etkIbM0LvrkQHLBIV6ENlIMxX5lz/YMxBp/J5pzkO6KG3TUQ20eQmBVovw0EI1lEox7J1GtLwENfBfcYFCy1us7df6/0JNI=
    lastmodified: "2026-04-29T11:57:41Z"
    mac: ENC[AES256_GCM,data:WI3KVDn3agD1viR4ckAbhfTwdPYFDqybfhjBxfeXBDFiCCzqwNAmRKpdyb+Qhwvl1wApLTpFTuWGHcjDuAPeWG11vrj7vbnHOZQe5WO7+YnI+NsbSaqC+mBBjU17xpNNUfG/SeOzllPLvE4FsZiRhwvHQWqIAvwKsUxRjmT79Gg=,iv:J4hHTsk0c7IsPDFLw/sR/BEAROnyN2eeHGG8LWkBSHA=,tag:Seh46sU6VLV8sxmlW6poYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
