config:
  args: ["clearnode"]
  logLevel: info
  database:
    driver: postgres
    host: pgbouncer
    port: 5432
    name: clearnode_stress_v1
    user: clearnode_stress_v1_admin
  envSecret: clearnode-secret-env
  extraEnvs: 
    CLEARNODE_DATABASE_MAX_OPEN_CONNS: "30"
    CLEARNODE_DATABASE_MAX_IDLE_CONNS: "10"
    CLEARNODE_DATABASE_CONN_MAX_LIFETIME_SEC: "3600"
    CLEARNODE_DATABASE_CONN_MAX_IDLE_TIME_SEC: "600"
    CLEARNODE_SIGNER_TYPE: "gcp-kms"
    CLEARNODE_GCP_KMS_KEY_NAME: "projects/ynet-stage/locations/europe-central2/keyRings/clearnode-signers-eu/cryptoKeys/stress-v1-a/cryptoKeyVersions/1"
    CLEARNODE_MAX_PARTICIPANTS: "32"
    CLEARNODE_MAX_SESSION_DATA_LEN: "1024"
    CLEARNODE_MAX_SIGNED_UPDATES: "0"
    CLEARNODE_MAX_SESSION_KEY_IDS: "256"

image:
  repository: ghcr.io/layer-3/nitrolite/clearnode
  tag: v1.2.0

service:
  http:
    enabled: true
    port: 7824
    path: /v1/ws

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: clearnode-stress-v1-agent@ynet-stage.iam.gserviceaccount.com

metrics:
  enabled: true
  podmonitoring:
    enabled: true
  port: 4242
  endpoint: "/metrics"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 256Mi
  requests:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 256Mi

autoscaling:
  enabled: false

networking:
  externalHostname: clearnode-stress.yellow.org
  tlsClusterIssuer: zerossl-prod
  gateway:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    tls:
      enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"

stressTest:
  enabled: false
