config:
    secretEnvs:
        CLEARNODE_BLOCKCHAIN_RPC_ETHEREUM_SEPOLIA: ENC[AES256_GCM,data:Qis/vy8w8KE/ap3xU1+gd2GqeGYRsQQBOld7tQ9YDEQx+jjQgsvyq3GMBrFytrsWeo24Zr+LrfWxP3iPcZdNQZRIgZbNgduNigt2nE77eZF8VZRm+0GqbMhwDlW663W0OVIWPmMnufSI8DZfo5niTfOU9LYhwxPi,iv:SpR+Twca+u7KH3XiIPbpqbidnqhXJobC4ytbj8Yr4/0=,tag:6CnwLthiSX9e8c+drbnFiA==,type:str]
        CLEARNODE_BLOCKCHAIN_RPC_BASE_SEPOLIA: ENC[AES256_GCM,data:ZYIrjPEBtjrVBt9tda4pJPLFEnbGHFAmLH2IrxVs8jfT2UqIhgYB+OZMUtorbj5GWNLVGv42T941eo/zceZ9Teon9J8fcojkgle2lqz5taz19S3h05LZTVHT7TADoR2UASsqKZk+5da41pEygl2iOh6iQPo=,iv:5zUIx4R0mlKqRNOExczKx2lo8x42Swi/4AhaOQipRNs=,tag:VsON7rLPg1cWTEyxlBWzeg==,type:str]
    database:
        password: ENC[AES256_GCM,data:wLVLlRQYE+e4rQ==,iv:2foG2y5yg2goA2fNLKMw9ESLJ9vVmS61ozbn9StQEuM=,tag:6Tl46uxUdMe12pMbSQ5XGg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/ynet-stage/locations/global/keyRings/sops/cryptoKeys/sops-uat-key
          created_at: "2026-04-02T12:14:10Z"
          enc: CiQAMMK76XoOsaEq3elJXL/OGZ/OvdDWr3hiLdfb5oQzSqJDrqESSQC9etkIbM0LvrkQHLBIV6ENlIMxX5lz/YMxBp/J5pzkO6KG3TUQ20eQmBVovw0EI1lEox7J1GtLwENfBfcYFCy1us7df6/0JNI=
    lastmodified: "2026-04-20T10:22:23Z"
    mac: ENC[AES256_GCM,data:0BO6+SogEqD8etCydhsoeZzHMJg55CawiP9aKWmBJIwTp0qc+idD5TRV1XQlBPVG+oE3UQLZUfySlLRL1MvDBll7M6OQs/sipGuYbWbpHg2ghj9SvSIEiYJvCBqvvwCSxL4zLzlu1qLL7WvbGJeDruZ3kYecJQO07Cgu3NoaT5o=,iv:CYWbxk34b3ioYr3V09OIXrTjOtU1TMmEADfg0xf1bNY=,tag:5BuEq3CybsIbVmQC8+6ckw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
