config:
    secretEnvs:
        CLEARNODE_BLOCKCHAIN_RPC_ETHEREUM_SEPOLIA: ENC[AES256_GCM,data:Qis/vy8w8KE/ap3xU1+gd2GqeGYRsQQBOld7tQ9YDEQx+jjQgsvyq3GMBrFytrsWeo24Zr+LrfWxP3iPcZdNQZRIgZbNgduNigt2nE77eZF8VZRm+0GqbMhwDlW663W0OVIWPmMnufSI8DZfo5niTfOU9LYhwxPi,iv:SpR+Twca+u7KH3XiIPbpqbidnqhXJobC4ytbj8Yr4/0=,tag:6CnwLthiSX9e8c+drbnFiA==,type:str]
        CLEARNODE_BLOCKCHAIN_RPC_POLYGON_AMOY: ENC[AES256_GCM,data:UDmEBTUc+q9qGs5p9dzVXRbIsW1SzlTskNefVkJ++jb+H1DR+Z+pIDwnKL9P9u3hTX4zrLDzGO21v8mVECl6cYMq/4b8AHsIvt1cxjTz464X1RrTrtuJXArwSuFFKyMIojlLRte240VDxGrhRO+BzwIOPSA/63Q=,iv:QhQSYfEp/lT1tohVBBmBbJdrctFcN0kXC+pamhoZUmE=,tag:vU/5PsoPFVr4OTQQhYRVNA==,type:str]
    database:
        password: ENC[AES256_GCM,data:wLVLlRQYE+e4rQ==,iv:2foG2y5yg2goA2fNLKMw9ESLJ9vVmS61ozbn9StQEuM=,tag:6Tl46uxUdMe12pMbSQ5XGg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/ynet-stage/locations/global/keyRings/sops/cryptoKeys/sops-uat-key
          created_at: "2026-04-02T12:14:10Z"
          enc: CiQAMMK76XoOsaEq3elJXL/OGZ/OvdDWr3hiLdfb5oQzSqJDrqESSQC9etkIbM0LvrkQHLBIV6ENlIMxX5lz/YMxBp/J5pzkO6KG3TUQ20eQmBVovw0EI1lEox7J1GtLwENfBfcYFCy1us7df6/0JNI=
    lastmodified: "2026-04-02T12:29:32Z"
    mac: ENC[AES256_GCM,data:/z776RGfHP6sVc/GzBN/UJ8KGf6KGtu+umE3hlQu9cnq3CjLe8oBVJg3CR9rsWlBwsgp9CB+3srzxvQLFEJ05HxjkwUfxt7bOu+MdydkzfWwrLRiV0MQgDGocLwmUpd8eew3pKNQzc89sWr6z9m8t8Sw3EYG7LmOmkqc0DwRgfo=,iv:nN/A08mDACrPNsZoRR9Xe1Ory9VU+TC9skPay/2kwm8=,tag:QFN45f+W1TXVONdcNLX+Mw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
