import { Address, Hex, encodeAbiParameters, keccak256, pad, toHex } from 'viem';
import { AppDefinitionV1, AppStateUpdateV1, AppSessionKeyStateV1, AppSessionVersionV1 } from './types';
import { AppV1 } from '../rpc/types';

/**
 * PackCreateAppSessionRequestV1 packs the Definition and SessionData for signing using ABI encoding.
 * This is used to generate a deterministic hash that participants sign when creating an app session.
 */
export function packCreateAppSessionRequestV1(definition: AppDefinitionV1, sessionData: string): `0x${string}` {
  // Define the participant tuple type components
  const participantComponents = [
    { name: 'walletAddress', type: 'address' },
    { name: 'signatureWeight', type: 'uint8' },
  ] as const;

  // Convert participants to the format expected by ABI packing
  const participants = definition.participants.map((p) => ({
    walletAddress: p.walletAddress,
    signatureWeight: p.signatureWeight,
  }));

  // Pack the data using ABI encoding
  const packed = encodeAbiParameters(
    [
      { type: 'string' }, // application
      { type: 'tuple[]', components: participantComponents }, // participants array
      { type: 'uint8' }, // quorum
      { type: 'uint64' }, // nonce
      { type: 'string' }, // sessionData
    ],
    [definition.applicationId, participants, definition.quorum, definition.nonce, sessionData],
  );

  // Return the Keccak256 hash of the packed data
  return keccak256(packed);
}

/**
 * PackAppStateUpdateV1 packs the AppStateUpdate for signing using ABI encoding.
 * This is used to generate a deterministic hash that participants sign when updating an app session state.
 */
export function packAppStateUpdateV1(stateUpdate: AppStateUpdateV1): `0x${string}` {
  // Define the allocation tuple type components
  const allocationComponents = [
    { name: 'participant', type: 'address' },
    { name: 'asset', type: 'string' },
    { name: 'amount', type: 'string' },
  ] as const;

  // Convert allocations to the format expected by ABI packing
  const allocations = stateUpdate.allocations.map((a) => ({
    participant: a.participant,
    asset: a.asset,
    amount: a.amount.toString(),
  }));

  // Convert app session ID from hex string to bytes32
  const appSessionIdHash = stateUpdate.appSessionId as `0x${string}`;

  // Pack the data using ABI encoding
  const packed = encodeAbiParameters(
    [
      { type: 'bytes32' }, // appSessionID
      { type: 'uint8' }, // intent
      { type: 'uint64' }, // version
      { type: 'tuple[]', components: allocationComponents }, // allocations array
      { type: 'string' }, // sessionData
    ],
    [appSessionIdHash, stateUpdate.intent, stateUpdate.version, allocations, stateUpdate.sessionData],
  );

  // Return the Keccak256 hash of the packed data
  return keccak256(packed);
}

/**
 * GenerateAppSessionIDV1 generates a deterministic app session ID from the definition using ABI encoding.
 */
export function generateAppSessionIDV1(definition: AppDefinitionV1): `0x${string}` {
  // Define the participant tuple type components
  const participantComponents = [
    { name: 'walletAddress', type: 'address' },
    { name: 'signatureWeight', type: 'uint8' },
  ] as const;

  // Convert participants to the format expected by ABI packing
  const participants = definition.participants.map((p) => ({
    walletAddress: p.walletAddress,
    signatureWeight: p.signatureWeight,
  }));

  // Pack the data using ABI encoding
  const packed = encodeAbiParameters(
    [
      { type: 'string' }, // application
      { type: 'tuple[]', components: participantComponents }, // participants array
      { type: 'uint8' }, // quorum
      { type: 'uint64' }, // nonce
    ],
    [definition.applicationId, participants, definition.quorum, definition.nonce],
  );

  // Return the Keccak256 hash as hex string
  return keccak256(packed);
}

/**
 * GenerateRebalanceBatchIDV1 creates a deterministic batch ID from session versions using ABI encoding.
 * The batch ID is generated by hashing the list of (sessionID, version) pairs.
 */
export function generateRebalanceBatchIDV1(sessionVersions: AppSessionVersionV1[]): `0x${string}` {
  // Define the session version tuple type components
  const sessionVersionComponents = [
    { name: 'sessionID', type: 'bytes32' },
    { name: 'version', type: 'uint64' },
  ] as const;

  // Convert session versions to the format expected by ABI packing
  const sessionVersionsArray = sessionVersions.map((sv) => ({
    sessionID: sv.sessionId as `0x${string}`,
    version: sv.version,
  }));

  // Pack the data using ABI encoding
  const packed = encodeAbiParameters(
    [
      { type: 'tuple[]', components: sessionVersionComponents }, // session versions array
    ],
    [sessionVersionsArray],
  );

  // Return the Keccak256 hash as hex string
  return keccak256(packed);
}

/**
 * GenerateRebalanceTransactionIDV1 creates a deterministic transaction ID for a rebalance transaction using ABI encoding.
 */
export function generateRebalanceTransactionIDV1(batchId: string, sessionId: string, asset: string): `0x${string}` {
  // Pack the data using ABI encoding
  const packed = encodeAbiParameters(
    [
      { type: 'bytes32' }, // batchID
      { type: 'bytes32' }, // sessionID
      { type: 'string' }, // asset
    ],
    [batchId as `0x${string}`, sessionId as `0x${string}`, asset],
  );

  // Return the Keccak256 hash as hex string
  return keccak256(packed);
}

/**
 * PackAppV1 packs the AppV1 for signing using ABI encoding.
 * Matches Go SDK's PackAppV1.
 *
 * @param app - The application definition to pack
 * @returns Keccak256 hash of the ABI-encoded app data
 */
export function packAppV1(app: AppV1): `0x${string}` {
  const metadataHash = keccak256(toHex(new TextEncoder().encode(app.metadata)));

  const packed = encodeAbiParameters(
    [
      { type: 'string' }, // id
      { type: 'address' }, // ownerWallet
      { type: 'bytes32' }, // metadata (hashed)
      { type: 'uint64' }, // version
      { type: 'bool' }, // creationApprovalNotRequired
    ],
    [app.id, app.owner_wallet as Address, metadataHash, BigInt(app.version), app.creation_approval_not_required],
  );

  return keccak256(packed);
}

/**
 * hexToBytes32 converts a hex string to a 32-byte value, matching Go's common.HexToHash behavior.
 * - Strips "0x" prefix if present
 * - Decodes hex characters; non-hex strings produce zero bytes
 * - Right-aligns the result in 32 bytes (left-padded with zeros)
 */
function hexToBytes32(s: string): Hex {
  // Strip 0x prefix
  let hex = s.startsWith('0x') || s.startsWith('0X') ? s.slice(2) : s;
  // Pad to even length
  if (hex.length % 2 === 1) {
    hex = '0' + hex;
  }
  // Validate hex characters - if any invalid char, return zero hash (matches Go behavior)
  if (!/^[0-9a-fA-F]*$/.test(hex)) {
    return pad('0x00', { size: 32 }) as Hex;
  }
  // If empty, return zero hash
  if (hex.length === 0) {
    return pad('0x00', { size: 32 }) as Hex;
  }
  // Truncate to 32 bytes max (64 hex chars)
  if (hex.length > 64) {
    hex = hex.slice(hex.length - 64);
  }
  // Left-pad to 64 hex chars (32 bytes)
  const padded = hex.padStart(64, '0');
  return `0x${padded}` as Hex;
}

/**
 * PackAppSessionKeyStateV1 packs the app session key state for signing using ABI encoding.
 * Matches Go SDK's PackAppSessionKeyStateV1.
 *
 * @param state - The app session key state to pack
 * @returns Keccak256 hash of the ABI-encoded state (excluding user_sig)
 */
export function packAppSessionKeyStateV1(state: AppSessionKeyStateV1): `0x${string}` {
  const applicationIDHashes = state.application_ids.map(hexToBytes32);
  const appSessionIDHashes = state.app_session_ids.map(hexToBytes32);

  const packed = encodeAbiParameters(
    [
      { type: 'address' }, // user_address
      { type: 'address' }, // session_key
      { type: 'uint64' }, // version
      { type: 'bytes32[]' }, // application_ids
      { type: 'bytes32[]' }, // app_session_ids
      { type: 'uint64' }, // expires_at
    ],
    [state.user_address as Address, state.session_key as Address, BigInt(state.version), applicationIDHashes, appSessionIDHashes, BigInt(state.expires_at)],
  );

  return keccak256(packed);
}
