config:
    secretEnvs:
        OWNER_PRIVATE_KEY: ENC[AES256_GCM,data:c54AOaPC1/b2MO/MK1h+i47HTCV9u7AF2zR6w/IDxYSc0r/NMmRbOauifKWikRFnDi4CXbjykqSx6ed60in9gg==,iv:fvY9/CguEUdAqjmH93ujsJZtOUgamfbNV81eh2AKttg=,tag:cLVQUWovRQqo3S7M+Kb9gg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/ynet-stage/locations/global/keyRings/sops/cryptoKeys/sops-uat-key
          created_at: "2026-05-25T11:37:38Z"
          enc: CiQAMMK76efRl7+42AnG9EjAWWg4BKgwkCTPh5zxNLMdKu+LC1cSSQC9etkICsswCHabKY9Uy4/b1eIrSUqTQWb5ISp3iHd/RMrQaBw3cMCI2OKvZgzvPyHRWv+dHfAet51VZSBVS57cw1T6yWNlQsk=
    lastmodified: "2026-05-25T11:38:27Z"
    mac: ENC[AES256_GCM,data:Loz3ojmAzqKDwKNn4DnuFRSDKG9okWnET8vlYwdMSTjt/KI+1xjO2JQOYJ1ekTvPilHYAwI/hUWSi+Yu7wR/NqG9ktNd/DDVpvo7DjlTUlAQgr+Cd2hXYaWtRRh7m6iT+NqcJxIA0CNQVwmlUK6XIEj/hh4bL43UPoyjK2+wxfY=,iv:iPNnuhRef+UlzT3S4qujX1x/1CMQDMg4tj0rnpryt24=,tag:pBmnKLSpo/D68RhV6NXYQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
