config:
    secretEnvs:
        OWNER_PRIVATE_KEY: ENC[AES256_GCM,data:YcDPaepdZ4g9JRq16aB/U2cMZ/4PvTydrkceNyjZ02lJBztyWUAtP00yuEgBT//n+HW6ZmTaHnCN+CdOIkZokw==,iv:lGsBd2Pa/5kx87YOlpVy5Wd87X0y89R6eAe/qrgMCLU=,tag:3uNT7i03jkRdg6B0fVp1Xg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/ynet-stage/locations/global/keyRings/sops/cryptoKeys/sops-uat-key
          created_at: "2026-05-25T11:37:43Z"
          enc: CiQAMMK76Uhrh3w/JAx38ps76DFbaO+J/OL438qmIPgtiEodLtcSSQC9etkIsBCWeg9HtapqEY2h2aT+6j5thcihCYuABKlBdzhAb5+JVFrPkOSRWzfjxcRjCqPY9jMh7EQcNs9ly76GzH8CExQTUbw=
    lastmodified: "2026-05-25T11:38:36Z"
    mac: ENC[AES256_GCM,data:e4hRk9RmrKtBWA7FvUrsb5UQEWNNfSq2hHEcxT6sNlj22djKAZgV+XI9SR+vQhX7LGrelhvFd2TdnTzIwG7GmVDshfpDee3YnkJBIUHs+l2mYLw6L36nlwzSwdU8AKCqxbOVvi42SaiNh+uPyqZYTvJVMBM9IFPbnbw5ZjFV2A8=,iv:8e3aaK1R5e1ONarRfUUpjCnDpXu8u/S1oj4XvcJn1ic=,tag:GbPJECvitkVF0WqyHf5G7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
