{{- if .Values.ghcrPullDockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearnode.common.fullname" . }}-ghcr-pull
  labels:
    {{- include "clearnode.common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.ghcrPullDockerConfigJson | quote }}
{{- end }}
