# yaml-language-server: $schema=../../../config/schemas/action_gateway_schema.yaml
level_step_tokens: "100"
app_cost: "200"
action_gates:
  transfer:
    free_actions_allowance: 10
    increase_per_level: 5
  app_session_creation:
    free_actions_allowance: 5
    increase_per_level: 2
  app_session_operation:
    free_actions_allowance: 20
    increase_per_level: 10
  app_session_deposit:
    free_actions_allowance: 15
    increase_per_level: 7
  app_session_withdrawal:
    free_actions_allowance: 15
    increase_per_level: 7
