name: PR on main branch

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test-nitronode:
    name: Test (Nitronode)
    uses: ./.github/workflows/test-go.yml

  test-forge:
    name: Test (Foundry)
    uses: ./.github/workflows/test-forge.yml

  # test-sdk:
  #   name: Test (SDK)
  #   uses: ./.github/workflows/test-sdk.yml
  #   with:
  #     project-path: 'sdk'
  #     project-name: 'SDK'

  build-and-publish-nitronode:
    name: Build and Publish (Nitronode)
    needs: test-nitronode
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./nitronode/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/nitronode:${{ steps.sha.outputs.short_sha }}
          cache-from: type=gha
          build-args: |
            VERSION=${{ steps.sha.outputs.short_sha }}

